Combo.create(:id => 3, :no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Masterscoot > Gainerflash > Backside 900 > Doubleleg")
Combo.create(:id => 4, :no_tricks => 3, :tricker_id => 1, :sequence => "540 > Cartwheel > Full Doubleleg")
Combo.create(:id => 5, :no_tricks => 6, :tricker_id => 1, :sequence => "Cartwheel > Front Flip > Front Roll > Back Sweep > Scoot > Cork Doubleleg")
Combo.create(:id => 6, :no_tricks => 3, :tricker_id => 1, :sequence => "Butterfly Twist > Cheat 900 > Doubleleg")
Combo.create(:id => 7, :no_tricks => 4, :tricker_id => 1, :sequence => "Hook > Cartwheel > Fulltwist > Gainerflash")
Combo.create(:id => 8, :no_tricks => 3, :tricker_id => 1, :sequence => "Cheat 900 > Hook > Jackknife")
Combo.create(:id => 9, :no_tricks => 4, :tricker_id => 1, :sequence => "Paraknife > Raiz > Cork Doubleleg > Backside 1080")
Combo.create(:id => 10, :no_tricks => 6, :tricker_id => 1, :sequence => "Hook > Raiz > Cheat 900 > Hook > Cartwheel > Doublefull")
Combo.create(:id => 11, :no_tricks => 3, :tricker_id => 1, :sequence => "Jackknife > Aerial > Grandmasterswipe")
Combo.create(:id => 22, :no_tricks => 3, :tricker_id => 1, :sequence => "Hook > Cheat 720 Twist > Fulltwist Round")
Combo.create(:id => 25, :no_tricks => 3, :tricker_id => 1, :sequence => "Boxcutter > Cheat Hyper 900 > Front Flip")
Combo.create(:id => 29, :no_tricks => 3, :tricker_id => 1, :sequence => "Snapuswipe > Flash Kick > Backside 1080")
Combo.create(:id => 30, :no_tricks => 4, :tricker_id => 1, :sequence => "Pop 1080 > Grandmasterswipe > Fulltwist > Cheat Hyper 900")
Combo.create(:id => 35, :no_tricks => 5, :tricker_id => 1, :sequence => "Cheat 900 > 540 > Front Sweep > Butterfly Twist > Gainerflash")
Combo.create(:id => 36, :no_tricks => 4, :tricker_id => 1, :sequence => "Cheat 720 Twist > Doublefull > Suicide Kip Up > Fulltwist Round")
Combo.create(:id => 44, :no_tricks => 3, :tricker_id => 1, :sequence => "Jackknife > Masterscoot > Cork Doubleleg")
Combo.create(:id => 54, :no_tricks => 5, :tricker_id => 1, :sequence => "Butterfly Twist > Full Doubleleg > Front Flip > Front Sweep > Backside 1080")
Combo.create(:id => 61, :no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Narabong > Sideswipe > Aerial > Doubleleg Hook")
Combo.create(:id => 62, :no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat 900 > Hook > Jackknife")
Combo.create(:id => 63, :no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat Hyper 900 > Cartwheel > Fulltwist")
Combo.create(:id => 67, :no_tricks => 5, :tricker_id => 1, :sequence => "B-Twist Round > Hook > 540 > Cartwheel > Full Doubleleg")
Combo.create(:id => 68, :no_tricks => 4, :tricker_id => 1, :sequence => "Cheat 900 > Hook > TD Raiz > Flash Kick")
Combo.create(:id => 71, :no_tricks => 7, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat Hyper 900 > Aerial > Narabong > TD Raiz > Flash Kick")
Combo.create(:id => 74, :no_tricks => 3, :tricker_id => 1, :sequence => "Pop 360 > Parafuso > Doubleleg")
Combo.create(:id => 77, :no_tricks => 5, :tricker_id => 1, :sequence => "Cheat 720 > Tornado Kick > Cheat 900 > Hook > Aerial Hook Grab")
Combo.create(:id => 78, :no_tricks => 5, :tricker_id => 1, :sequence => "Cartwheel > Back Flip > Back Roll > Back Handspring > Flash Kick")
Combo.create(:id => 79, :no_tricks => 5, :tricker_id => 1, :sequence => "Pop 360 > Back Sweep > Narabong > TD Raiz > Flash Kick")
Combo.create(:id => 80, :no_tricks => 5, :tricker_id => 1, :sequence => "Tornado Kick > Cheat 900 > Hook > Raiz > Flash Kick")
Combo.create(:id => 81, :no_tricks => 5, :tricker_id => 1, :sequence => "Hook > 540 > TD Raiz > Gainer Switch > Corkscrew")
Combo.create(:id => 83, :no_tricks => 4, :tricker_id => 1, :sequence => "Tornado Kick > Cheat 1080 > Raiz > Gainerflash")
Combo.create(:id => 84, :no_tricks => 3, :tricker_id => 1, :sequence => "Pop 720 Double > TD Raiz > Terada Grab")
