List.create(:id => 1, :tricker_id => 1, :name => "Favorites", :visibility => "Public")
List.create(:id => 2, :tricker_id => 1, :name => "Working on", :visibility => "Public")
List.create(:id => 3, :tricker_id => 1, :name => "Landed", :visibility => "Public")
List.create(:id => 4, :tricker_id => 2, :name => "Favorites", :visibility => "Public")
List.create(:id => 5, :tricker_id => 2, :name => "Working on", :visibility => "Public")
List.create(:id => 6, :tricker_id => 2, :name => "Landed", :visibility => "Public")
List.create(:id => 7, :name => "Favorites", :visibility => "Public")
List.create(:id => 8, :name => "Working on", :visibility => "Public")
List.create(:id => 9, :name => "Landed", :visibility => "Public")
List.create(:id => 10, :name => "Favorites", :visibility => "Public")
List.create(:id => 11, :name => "Working on", :visibility => "Public")
List.create(:id => 12, :name => "Landed", :visibility => "Public")
List.create(:id => 13, :name => "Favorites", :visibility => "Public")
List.create(:id => 14, :name => "Working on", :visibility => "Public")
List.create(:id => 15, :name => "Landed", :visibility => "Public")
List.create(:id => 16, :name => "Favorites", :visibility => "Public")
List.create(:id => 17, :name => "Working on", :visibility => "Public")
List.create(:id => 18, :name => "Landed", :visibility => "Public")
List.create(:id => 19, :name => "Favorites", :visibility => "Public")
List.create(:id => 20, :name => "Working on", :visibility => "Public")
List.create(:id => 21, :name => "Landed", :visibility => "Public")
List.create(:id => 22, :name => "Favorites", :visibility => "Public")
List.create(:id => 23, :name => "Working on", :visibility => "Public")
List.create(:id => 24, :name => "Landed", :visibility => "Public")
List.create(:id => 25, :name => "Favorites", :visibility => "Public")
List.create(:id => 26, :name => "Working on", :visibility => "Public")
List.create(:id => 27, :name => "Landed", :visibility => "Public")
List.create(:id => 28, :name => "Favorites", :visibility => "Public")
List.create(:id => 29, :name => "Working on", :visibility => "Public")
List.create(:id => 30, :name => "Landed", :visibility => "Public")
List.create(:id => 31, :name => "Favorites", :visibility => "Public")
List.create(:id => 32, :name => "Working on", :visibility => "Public")
List.create(:id => 33, :name => "Landed", :visibility => "Public")
