TrickingStyle.create(:id => 1, :tricker_id => 1, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 2, :tricker_id => 2, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 3, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 4, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 5, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 6, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 7, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 8, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 9, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 10, :name => "My Trick List", :description => "All the tricks I can do.")
TrickingStyle.create(:id => 11, :name => "My Trick List", :description => "All the tricks I can do.")
