Trick.create(:id => 1, :name => "540", :difficulty => "A", :trick_type => "Kick")
Trick.create(:id => 2, :name => "Tornado Kick", :difficulty => "FND", :trick_type => "Kick")
Trick.create(:id => 3, :name => "Cartwheel", :difficulty => "FND", :trick_type => "N/A")
Trick.create(:id => 4, :name => "Hook", :difficulty => "FND", :trick_type => "Kick")
Trick.create(:id => 5, :name => "Front Roll", :difficulty => "FND", :trick_type => "N/A")
Trick.create(:id => 6, :name => "Back Roll", :difficulty => "FND", :trick_type => "N/A")
Trick.create(:id => 7, :name => "Pop 360", :difficulty => "A", :trick_type => "Kick")
Trick.create(:id => 8, :name => "Aerial", :difficulty => "A", :trick_type => "Invert")
Trick.create(:id => 9, :name => "Back Flip", :difficulty => "A", :trick_type => "Flip")
Trick.create(:id => 10, :name => "Front Flip", :difficulty => "A", :trick_type => "Flip")
Trick.create(:id => 11, :name => "Butterfly Kick", :difficulty => "A", :trick_type => "Kick")
Trick.create(:id => 12, :name => "Kip Up", :difficulty => "A", :trick_type => "N/A")
Trick.create(:id => 13, :name => "Feilong Kick", :difficulty => "A", :trick_type => "Kick")
Trick.create(:id => 14, :name => "Au Batido", :difficulty => "A", :trick_type => "N/A")
Trick.create(:id => 15, :name => "Cheat 720", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 16, :name => "Aerial Switch", :difficulty => "B", :trick_type => "Invert")
Trick.create(:id => 17, :name => "Butterfly Twist", :difficulty => "B", :trick_type => "Twist")
Trick.create(:id => 18, :name => "Doubleleg", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 19, :name => "Pop 720", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 20, :name => "Flash Kick", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 21, :name => "Raiz", :difficulty => "B", :trick_type => "Invert")
Trick.create(:id => 22, :name => "TD Raiz", :difficulty => "B", :trick_type => "Invert")
Trick.create(:id => 23, :name => "Parafuso", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 24, :name => "Gainerflash", :difficulty => "B", :trick_type => "Flip")
Trick.create(:id => 25, :name => "Masterswipe", :difficulty => "B", :trick_type => "Invert")
Trick.create(:id => 26, :name => "Suicide Kip Up", :difficulty => "B", :trick_type => "N/A")
Trick.create(:id => 27, :name => "Backside 900", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 28, :name => "Sideswipe", :difficulty => "C", :trick_type => "Kick")
Trick.create(:id => 29, :name => "Hypertwist", :difficulty => "C", :trick_type => "Twist")
Trick.create(:id => 30, :name => "Pop 900", :difficulty => "C", :trick_type => "Kick")
Trick.create(:id => 31, :name => "Backside 1080", :difficulty => "C", :trick_type => "Kick")
Trick.create(:id => 32, :name => "Jackknife", :difficulty => "C", :trick_type => "Kick")
Trick.create(:id => 33, :name => "Corkscrew", :difficulty => "C", :trick_type => "Flip, Twist")
Trick.create(:id => 34, :name => "Cheat 900", :difficulty => "C", :trick_type => "Kick")
Trick.create(:id => 35, :name => "Aerial Twist", :difficulty => "C", :trick_type => "Twist")
Trick.create(:id => 36, :name => "Fulltwist", :difficulty => "C", :trick_type => "Flip, Twist")
Trick.create(:id => 37, :name => "Terada Grab", :difficulty => "C", :trick_type => "Kick, Flip")
Trick.create(:id => 38, :name => "X-Out", :difficulty => "C", :trick_type => "Kick, Flip")
Trick.create(:id => 39, :name => "Grandmasterswipe", :difficulty => "C", :trick_type => "Invert")
Trick.create(:id => 40, :name => "Pop 1080", :difficulty => "D", :trick_type => "Kick")
Trick.create(:id => 41, :name => "Doubleleg Hook", :difficulty => "D", :trick_type => "Kick")
Trick.create(:id => 42, :name => "Cheat 720 Twist", :difficulty => "D", :trick_type => "Twist")
Trick.create(:id => 43, :name => "Boxcutter", :difficulty => "D", :trick_type => "Flip, Twist, Kick")
Trick.create(:id => 44, :name => "Paraknife", :difficulty => "D", :trick_type => "Kick")
Trick.create(:id => 45, :name => "Hyperhook", :difficulty => "D", :trick_type => "Kick, Twist")
Trick.create(:id => 46, :name => "Cork Doubleleg", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create(:id => 47, :name => "Full Doubleleg", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create(:id => 48, :name => "Fulltwist Round", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create(:id => 49, :name => "Snapuswipe", :difficulty => "E", :trick_type => "Kick, Twist")
Trick.create(:id => 50, :name => "Doublefull", :difficulty => "E", :trick_type => "Flip, Twist")
Trick.create(:id => 51, :name => "Cheat 900 Double", :difficulty => "E", :trick_type => "Kick")
Trick.create(:id => 52, :name => "Cheat Hyper 900", :difficulty => "E", :trick_type => "Kick")
Trick.create(:id => 53, :name => "Cheat 1080", :difficulty => "E", :trick_type => "Kick")
Trick.create(:id => 54, :name => "Double B-Twist", :difficulty => "E", :trick_type => "Twist")
Trick.create(:id => 55, :name => "Doubleleg Twist", :difficulty => "E", :trick_type => "Kick")
Trick.create(:id => 56, :name => "Masterscoot", :difficulty => "EX", :trick_type => "N/A")
Trick.create(:id => 57, :name => "Scoot", :difficulty => "EX", :trick_type => "N/A")
Trick.create(:id => 58, :name => "Front Sweep", :difficulty => "EX", :trick_type => "Kick")
Trick.create(:id => 59, :name => "Back Sweep", :difficulty => "EX", :trick_type => "Kick")
Trick.create(:id => 60, :name => "Narabong", :difficulty => "EX", :trick_type => "Kick")
Trick.create(:id => 71, :name => "Double Cork", :difficulty => "E", :trick_type => "Twist")
Trick.create(:id => 72, :name => "B-Twist Round", :difficulty => "B", :trick_type => "Kick, Twist")
Trick.create(:id => 73, :name => "Hyper Dleg", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 74, :name => "Aerial Hook Grab", :difficulty => "B", :trick_type => "Kick")
Trick.create(:id => 75, :name => "Back Handspring", :difficulty => "A", :trick_type => "Flip")
Trick.create(:id => 76, :name => "Gainer Switch", :difficulty => "B", :trick_type => "Flip")
Trick.create(:id => 77, :name => "Pop 720 Double", :difficulty => "C", :trick_type => "Kick")
