Video.create(:id => 3, :trick_id => 1, :tricker_id => 1, :url => "www.youtube.com/watch?v=QjOepEGrO8s")
Video.create(:id => 4, :trick_id => 8, :tricker_id => 1, :url => "www.youtube.com/watch?v=NDpgshR6s4g")
Video.create(:id => 5, :trick_id => 7, :tricker_id => 1, :url => "www.youtube.com/watch?v=7_aDn5zdcPE")
Video.create(:id => 6, :trick_id => 17, :tricker_id => 1, :url => "www.youtube.com/watch?v=G_bpuAz9eIM")
Video.create(:id => 7, :trick_id => 18, :tricker_id => 1, :url => "www.youtube.com/watch?v=IgxGSUQ0jLg")
Video.create(:id => 8, :trick_id => 20, :tricker_id => 1, :url => "www.youtube.com/watch?v=9w8owtFTihc")
Video.create(:id => 9, :trick_id => 32, :tricker_id => 1, :url => "www.youtube.com/watch?v=dkRM3MeSRXI")
Video.create(:id => 10, :combo_id => 6, :tricker_id => 1, :url => "http://www.youtube.com/watch?v=zEGtgVM6NzE", :start_time => 99, :end_time => 103)
Video.create(:id => 12, :combo_id => 68, :url => "http://www.youtube.com/watch?v=yps2VZIQZz8", :start_time => 75, :end_time => 80)
Video.create(:id => 13, :combo_id => 67, :url => "www.youtube.com/watch?v=9DDuwCHyy1g", :start_time => 48, :end_time => 54)
Video.create(:id => 14, :combo_id => 71, :url => "www.youtube.com/watch?v=zEGtgVM6NzE", :start_time => 148, :end_time => 157)
Video.create(:id => 15, :combo_id => 72, :url => "www.youtube.com/watch?v=zEGtgVM6NzE", :start_time => 1, :end_time => 10)
Video.create(:id => 18, :combo_id => 74, :url => "www.youtube.com/watch?v=zEGtgVM6NzE", :start_time => 145, :end_time => 148)
Video.create(:id => 21, :combo_id => 63, :url => "http://www.youtube.com/watch?v=hmNBPXG05iw", :start_time => 213, :end_time => 218)
Video.create(:id => 22, :combo_id => 54, :url => "http://www.youtube.com/watch?v=hmNBPXG05iw", :start_time => 9999, :end_time => 9999)
Video.create(:id => 23, :combo_id => 77, :url => "http://www.youtube.com/watch?v=EsWSB0EFbtQ", :start_time => 31, :end_time => 37)
Video.create(:id => 24, :combo_id => 78, :url => "http://www.youtube.com/watch?v=EsWSB0EFbtQ", :start_time => 44, :end_time => 51)
Video.create(:id => 25, :combo_id => 79, :url => "http://www.youtube.com/watch?v=EsWSB0EFbtQ", :start_time => 8, :end_time => 18)
Video.create(:id => 30, :combo_id => 11, :url => "http://www.youtube.com/watch?v=1PMJyFEhQWA", :start_time => 327, :end_time => 333)
Video.create(:id => 33, :combo_id => 5, :url => "www.youtube.com/watch?v=9DDuwCHyy1g", :start_time => 94, :end_time => 100)
Video.create(:id => 34, :combo_id => 81, :url => "www.youtube.com/watch?v=9DDuwCHyy1g", :start_time => 62, :end_time => 68)
Video.create(:id => 40)
Video.create(:id => 41, :combo_id => 80, :url => "http://www.youtube.com/watch?v=0KG9xnCvGDk", :start_time => 203, :end_time => 210)
Video.create(:id => 42, :combo_id => 84, :url => "http://www.youtube.com/watch?v=M-7ivrZAGVY", :start_time => 170, :end_time => 175)
