# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Trick.create(name: "540", difficulty: "A", setup: "Cheat")
Trick.create(name: "Pop 360", difficulty: "A", setup: "Pop")
Trick.create(name: "Aerial", difficulty: "A", setup: "N/A")
Trick.create(name: "Backflip", difficulty: "A", setup: "N/A")
Trick.create(name: "Butterfly Kick", difficulty: "A", setup: "N/A")
Trick.create(name: "Kip Up", difficulty: "A", setup: "N/A")
Trick.create(name: "Feilong Kick", difficulty: "A", setup: "Pop")
Trick.create(name: "Au Batido", difficulty: "A", setup: "N/A")
Trick.create(name: "Cheat 720", difficulty: "B", setup: "Cheat")
Trick.create(name: "Aerial Switch", difficulty: "B", setup: "N/A")
Trick.create(name: "Butterfly Twist", difficulty: "B", setup: "N/A")
Trick.create(name: "Doubleleg", difficulty: "B", setup: "Pop")
Trick.create(name: "Pop 720", difficulty: "B", setup: "Pop")
Trick.create(name: "Flash Kick", difficulty: "B", setup: "N/A")
Trick.create(name: "Raiz", difficulty: "B", setup: "N/A")
Trick.create(name: "Parafuso", difficulty: "B", setup: "Cheat")
Trick.create(name: "Gainerflash", difficulty: "B", setup: "Swing")
Trick.create(name: "Masterswipe", difficulty: "B", setup: "Master")
Trick.create(name: "Sideswipe", difficulty: "C", setup: "N/A")
Trick.create(name: "Hypertwist", difficulty: "C", setup: "N/A")
Trick.create(name: "Pop 900", difficulty: "C", setup: "Pop")
Trick.create(name: "Jackknife", difficulty: "C", setup: "Cheat")
Trick.create(name: "Corkscrew", difficulty: "C", setup: "Swing")
Trick.create(name: "Cheat 900", difficulty: "C", setup: "Cheat")
Trick.create(name: "Aerial Twist", difficulty: "C", setup: "N/A")
Trick.create(name: "Terada Grab", difficulty: "C", setup: "N/A")
Trick.create(name: "X-Out", difficulty: "C", setup: "N/A")
Trick.create(name: "Grandmasterswipe", difficulty: "C", setup: "Master")
Trick.create(name: "Pop 1080", difficulty: "D", setup: "Pop")
Trick.create(name: "Doubleleg Hook", difficulty: "D", setup: "Pop")
Trick.create(name: "Cheat 720 Twist", difficulty: "D", setup: "N/A")
Trick.create(name: "Boxcutter", difficulty: "D", setup: "Swing")
Trick.create(name: "Paraknife", difficulty: "D", setup: "Cheat")
Trick.create(name: "Hyperhook", difficulty: "D", setup: "N/A")
Trick.create(name: "Cork Doubleleg", difficulty: "D", setup: "Swing")
Trick.create(name: "Fulltwist Round", difficulty: "D", setup: "N/A")
Trick.create(name: "Full Doubleleg", difficulty: "D", setup: "N/A")
Trick.create(name: "Snapuswipe", difficulty: "E", setup: "N/A")
Trick.create(name: "Doublefull", difficulty: "E", setup: "N/A")
Trick.create(name: "Cheat 900 Double", difficulty: "E", setup: "Cheat")
Trick.create(name: "Cheat Hyper 900", difficulty: "E", setup: "Cheat")
Trick.create(name: "Cheat 1080", difficulty: "E", setup: "Cheat")
Trick.create(name: "Double B-Twist", difficulty: "E", setup: "N/A")
Trick.create(name: "Doubleleg Twist", difficulty: "E", setup: "Pop")