# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).

# TRICKS
Trick.create(name: "Tornado Kick", difficulty: "FND", trick_type: "Kick")
Trick.create(name: "Cartwheel", difficulty: "FND", trick_type: "N/A")
Trick.create(name: "Hook", difficulty: "FND", trick_type: "Kick")
Trick.create(name: "Front Roll", difficulty: "FND", trick_type: "N/A")
Trick.create(name: "Back Roll", difficulty: "FND", trick_type: "N/A")
Trick.create(name: "540", difficulty: "A", trick_type: "Kick")
Trick.create(name: "Pop 360", difficulty: "A", trick_type: "Kick")
Trick.create(name: "Aerial", difficulty: "A", trick_type: "N/A")
Trick.create(name: "Back Flip", difficulty: "A", trick_type: "N/A")
Trick.create(name: "Front Flip", difficulty: "A", trick_type: "N/A")
Trick.create(name: "Butterfly Kick", difficulty: "A", trick_type: "Kick")
Trick.create(name: "Kip Up", difficulty: "A", trick_type: "N/A")
Trick.create(name: "Feilong Kick", difficulty: "A", trick_type: "Kick")
Trick.create(name: "Au Batido", difficulty: "A", trick_type: "N/A")
Trick.create(name: "Cheat 720", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Aerial Switch", difficulty: "B", trick_type: "Invert")
Trick.create(name: "Butterfly Twist", difficulty: "B", trick_type: "Twist")
Trick.create(name: "Doubleleg", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Pop 720", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Flash Kick", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Raiz", difficulty: "B", trick_type: "N/A")
Trick.create(name: "TD Raiz", difficulty: "B", trick_type: "N/A")
Trick.create(name: "Parafuso", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Gainerflash", difficulty: "B", trick_type: "Flip")
Trick.create(name: "Masterswipe", difficulty: "B", trick_type: "Invert")
Trick.create(name: "Suicide Kip Up", difficulty: "B", trick_type: "N/A")
Trick.create(name: "Backside 900", difficulty: "B", trick_type: "Kick")
Trick.create(name: "Sideswipe", difficulty: "C", trick_type: "Kick")
Trick.create(name: "Hypertwist", difficulty: "C", trick_type: "Twist")
Trick.create(name: "Pop 900", difficulty: "C", trick_type: "Kick")
Trick.create(name: "Backside 1080", difficulty: "C", trick_type: "Kick")
Trick.create(name: "Jackknife", difficulty: "C", trick_type: "Kick")
Trick.create(name: "Corkscrew", difficulty: "C", trick_type: "Flip, Twist")
Trick.create(name: "Cheat 900", difficulty: "C", trick_type: "Kick")
Trick.create(name: "Aerial Twist", difficulty: "C", trick_type: "Twist")
Trick.create(name: "Fulltwist", difficulty: "C", trick_type: "Flip, Twist")
Trick.create(name: "Terada Grab", difficulty: "C", trick_type: "N/A")
Trick.create(name: "X-Out", difficulty: "C", trick_type: "N/A")
Trick.create(name: "Grandmasterswipe", difficulty: "C", trick_type: "Invert")
Trick.create(name: "Pop 1080", difficulty: "D", trick_type: "Kick")
Trick.create(name: "Doubleleg Hook", difficulty: "D", trick_type: "Kick")
Trick.create(name: "Cheat 720 Twist", difficulty: "D", trick_type: "N/A")
Trick.create(name: "Boxcutter", difficulty: "D", trick_type: "Flip, Twist, Kick")
Trick.create(name: "Paraknife", difficulty: "D", trick_type: "Kick")
Trick.create(name: "Hyperhook", difficulty: "D", trick_type: "Kick, Twist")
Trick.create(name: "Cork Doubleleg", difficulty: "D", trick_type: "Kick, Flip, Twist")
Trick.create(name: "Full Doubleleg", difficulty: "D", trick_type: "Kick, Flip, Twist")
Trick.create(name: "Fulltwist Round", difficulty: "D", trick_type: "Kick, Flip, Twist")
Trick.create(name: "Full Doubleleg", difficulty: "D", trick_type: "N/A")
Trick.create(name: "Snapuswipe", difficulty: "E", trick_type: "N/A")
Trick.create(name: "Doublefull", difficulty: "E", trick_type: "N/A")
Trick.create(name: "Cheat 900 Double", difficulty: "E", trick_type: "Kick")
Trick.create(name: "Cheat Hyper 900", difficulty: "E", trick_type: "Kick")
Trick.create(name: "Cheat 1080", difficulty: "E", trick_type: "Kick")
Trick.create(name: "Double B-Twist", difficulty: "E", trick_type: "N/A")
Trick.create(name: "Doubleleg Twist", difficulty: "E", trick_type: "Kick")
Trick.create(name: "Masterscoot", difficulty: "EX", trick_type: "N/A")
Trick.create(name: "Scoot", difficulty: "EX", trick_type: "N/A")
Trick.create(name: "Front Sweep", difficulty: "EX", trick_type: "N/A")
Trick.create(name: "Back Sweep", difficulty: "EX", trick_type: "N/A")
Trick.create(name: "Narabong", difficulty: "EX", trick_type: "N/A")


# COMBOS
Combo.create(:no_tricks => 4)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Cheat 900").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("TD Raiz").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Flash Kick").id )

Combo.create(:no_tricks => 5)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Masterscoot").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Gainerflash").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Backside 900").id )
Element.create(:combo_id => Combo.last.id, :index => 5, :trick_id => Trick.find_by_name("Doubleleg").id )

Combo.create(:no_tricks => 3)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("540").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Cartwheel").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Full Doubleleg").id )

Combo.create(:no_tricks => 6)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Cartwheel").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Front Flip").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Front Roll").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Back Sweep").id )
Element.create(:combo_id => Combo.last.id, :index => 5, :trick_id => Trick.find_by_name("Scoot").id )
Element.create(:combo_id => Combo.last.id, :index => 6, :trick_id => Trick.find_by_name("Cork Doubleleg").id )

Combo.create(:no_tricks => 3)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Butterfly Twist").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Cheat 900").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Doubleleg").id )

Combo.create(:no_tricks => 4)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Cartwheel").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Fulltwist").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Gainerflash").id )

Combo.create(:no_tricks => 3)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Cheat 900").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Jackknife").id )

Combo.create(:no_tricks => 4)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Paraknife").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Raiz").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Cork Doubleleg").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Backside 1080").id )

Combo.create(:no_tricks => 6)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Raiz").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Cheat 900").id )
Element.create(:combo_id => Combo.last.id, :index => 4, :trick_id => Trick.find_by_name("Hook").id )
Element.create(:combo_id => Combo.last.id, :index => 5, :trick_id => Trick.find_by_name("Cartwheel").id )
Element.create(:combo_id => Combo.last.id, :index => 6, :trick_id => Trick.find_by_name("Doublefull").id )

Combo.create(:no_tricks => 3)
Element.create(:combo_id => Combo.last.id, :index => 1, :trick_id => Trick.find_by_name("Jackknife").id )
Element.create(:combo_id => Combo.last.id, :index => 2, :trick_id => Trick.find_by_name("Aerial").id )
Element.create(:combo_id => Combo.last.id, :index => 3, :trick_id => Trick.find_by_name("Grandmasterswipe").id )



# TUTORIALS

Video.create(tricker_id: 1, trick_id: Trick.find_by_name("540").id, url: "www.youtube.com/watch?v=QjOepEGrO8s")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Aerial").id, url: "www.youtube.com/watch?v=NDpgshR6s4g")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Backflip").id, url: "www.youtube.com/watch?v=BjgMjA_iIgw")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Pop 360").id, url: "www.youtube.com/watch?v=7_aDn5zdcPE")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Butterfly Twist").id, url: "www.youtube.com/watch?v=G_bpuAz9eIM")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Doubleleg").id, url: "www.youtube.com/watch?v=IgxGSUQ0jLg")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Flash Kick").id, url: "www.youtube.com/watch?v=9w8owtFTihc")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Sideswipe").id, url: "www.youtube.com/watch?v=k864os9ouog")
Video.create(tricker_id: 1, trick_id: Trick.find_by_name("Jackknife").id, url: "www.youtube.com/watch?v=dkRM3MeSRXI")
