Trick.create( :name => "540", :difficulty => "A", :trick_type => "Kick")
Trick.create( :name => "Tornado Kick", :difficulty => "FND", :trick_type => "Kick")
Trick.create( :name => "Cartwheel", :difficulty => "FND", :trick_type => "N/A")
Trick.create( :name => "Hook", :difficulty => "FND", :trick_type => "Kick")
Trick.create( :name => "Front Roll", :difficulty => "FND", :trick_type => "N/A")
Trick.create( :name => "Back Roll", :difficulty => "FND", :trick_type => "N/A")
Trick.create( :name => "Pop 360", :difficulty => "A", :trick_type => "Kick")
Trick.create( :name => "Aerial", :difficulty => "A", :trick_type => "Invert")
Trick.create( :name => "Back Flip", :difficulty => "A", :trick_type => "Flip")
Trick.create( :name => "Front Flip", :difficulty => "A", :trick_type => "Flip")
Trick.create( :name => "Butterfly Kick", :difficulty => "A", :trick_type => "Kick")
Trick.create( :name => "Kip Up", :difficulty => "A", :trick_type => "N/A")
Trick.create( :name => "Feilong Kick", :difficulty => "A", :trick_type => "Kick")
Trick.create( :name => "Au Batido", :difficulty => "A", :trick_type => "N/A")
Trick.create( :name => "Cheat 720", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Aerial Switch", :difficulty => "B", :trick_type => "Invert")
Trick.create( :name => "Butterfly Twist", :difficulty => "B", :trick_type => "Twist")
Trick.create( :name => "Doubleleg", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Pop 720", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Flash Kick", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Raiz", :difficulty => "B", :trick_type => "Invert")
Trick.create( :name => "TD Raiz", :difficulty => "B", :trick_type => "Invert")
Trick.create( :name => "Parafuso", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Gainerflash", :difficulty => "B", :trick_type => "Flip")
Trick.create( :name => "Masterswipe", :difficulty => "B", :trick_type => "Invert")
Trick.create( :name => "Suicide Kip Up", :difficulty => "B", :trick_type => "N/A")
Trick.create( :name => "Backside 900", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Sideswipe", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Hypertwist", :difficulty => "C", :trick_type => "Twist")
Trick.create( :name => "Pop 900", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Backside 1080", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Jackknife", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Corkscrew", :difficulty => "C", :trick_type => "Flip, Twist")
Trick.create( :name => "Cheat 900", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Aerial Twist", :difficulty => "C", :trick_type => "Twist")
Trick.create( :name => "Fulltwist", :difficulty => "C", :trick_type => "Flip, Twist")
Trick.create( :name => "Terada Grab", :difficulty => "C", :trick_type => "Kick, Flip")
Trick.create( :name => "X-Out", :difficulty => "C", :trick_type => "Kick, Flip")
Trick.create( :name => "Grandmasterswipe", :difficulty => "C", :trick_type => "Invert")
Trick.create( :name => "Pop 1080", :difficulty => "D", :trick_type => "Kick")
Trick.create( :name => "Doubleleg Hook", :difficulty => "D", :trick_type => "Kick")
Trick.create( :name => "Cheat 720 Twist", :difficulty => "D", :trick_type => "Twist")
Trick.create( :name => "Boxcutter", :difficulty => "D", :trick_type => "Flip, Twist, Kick")
Trick.create( :name => "Paraknife", :difficulty => "D", :trick_type => "Kick")
Trick.create( :name => "Hyperhook", :difficulty => "D", :trick_type => "Kick, Twist")
Trick.create( :name => "Cork Doubleleg", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create( :name => "Full Doubleleg", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create( :name => "Fulltwist Round", :difficulty => "D", :trick_type => "Kick, Flip, Twist")
Trick.create( :name => "Snapuswipe", :difficulty => "E", :trick_type => "Kick, Twist")
Trick.create( :name => "Doublefull", :difficulty => "E", :trick_type => "Flip, Twist")
Trick.create( :name => "Cheat 900 Double", :difficulty => "E", :trick_type => "Kick")
Trick.create( :name => "Cheat Hyper 900", :difficulty => "E", :trick_type => "Kick")
Trick.create( :name => "Cheat 1080", :difficulty => "E", :trick_type => "Kick")
Trick.create( :name => "Double B-Twist", :difficulty => "E", :trick_type => "Twist")
Trick.create( :name => "Doubleleg Twist", :difficulty => "E", :trick_type => "Kick, Twist")
Trick.create( :name => "Masterscoot", :difficulty => "EX", :trick_type => "N/A")
Trick.create( :name => "Scoot", :difficulty => "EX", :trick_type => "N/A")
Trick.create( :name => "Front Sweep", :difficulty => "EX", :trick_type => "Kick")
Trick.create( :name => "Back Sweep", :difficulty => "EX", :trick_type => "Kick")
Trick.create( :name => "Narabong", :difficulty => "EX", :trick_type => "Kick")
Trick.create( :name => "Double Cork", :difficulty => "E", :trick_type => "Twist")
Trick.create( :name => "B-Twist Round", :difficulty => "B", :trick_type => "Kick, Twist")
Trick.create( :name => "Hyper Dleg", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Aerial Hook Grab", :difficulty => "B", :trick_type => "Kick")
Trick.create( :name => "Back Handspring", :difficulty => "A", :trick_type => "Flip")
Trick.create( :name => "Gainer Switch", :difficulty => "B", :trick_type => "Flip")
Trick.create( :name => "Pop 720 Double", :difficulty => "C", :trick_type => "Kick")
Trick.create( :name => "Hyper Aerial", :difficulty => "C", :trick_type => "Invert" )

Trick.create( :name => "Webster", :difficulty => "B", :trick_type => "Flip" )
Trick.create( :name => "Round Off", :difficulty => "A", :trick_type => "Flip" )

# Combos
Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Masterscoot > Gainerflash > Backside 900 > Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Masterscoot").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Gainerflash").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Backside 900").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Doubleleg").id, :index => 5)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "540 > Cartwheel > Full Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Full Doubleleg").id, :index => 3)

Combo.create(:no_tricks => 6, :tricker_id => 1, :sequence => "Cartwheel > Front Flip > Front Roll > Back Sweep > Scoot > Cork Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Flip").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Roll").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Back Sweep").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Scoot").id, :index => 5)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cork Doubleleg").id, :index => 6)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Butterfly Twist > Cheat 900 > Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Full Doubleleg").id, :index => 3)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Hook > Cartwheel > Fulltwist > Gainerflash")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Fulltwist").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Gainerflash").id, :index => 4)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Cheat 900 > Hook > Jackknife")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Jackknife").id, :index => 3)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Paraknife > Raiz > Cork Doubleleg > Backside 1080")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Paraknife").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Raiz").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cork Doubleleg").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Backside 1080").id, :index => 4)

Combo.create(:no_tricks => 6, :tricker_id => 1, :sequence => "Hook > Raiz > Cheat 900 > Hook > Cartwheel > Doublefull")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Raiz").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 5)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Doublefull").id, :index => 6)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Jackknife > Aerial > Grandmasterswipe")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Jackknife").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Aerial").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Grandmasterswipe").id, :index => 3)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Hook > Cheat 720 Twist > Fulltwist Round")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 720 Twist").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Fulltwist Round").id, :index => 3)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Boxcutter > Cheat Hyper 900 > Front Flip")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Boxcutter").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat Hyper 900").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Flip").id, :index => 3)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Snapuswipe > Flash Kick > Backside 1080")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Snapuswipe").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Flash Kick").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Backside 1080").id, :index => 3)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Pop 1080 > Grandmasterswipe > Fulltwist > Cheat Hyper 900")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Pop 1080").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Grandmasterswipe").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Fulltwist").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat Hyper 900").id, :index => 4)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Cheat 900 > 540 > Front Sweep > Butterfly Twist > Gainerflash")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Sweep").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Butterfly Twist").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Gainerflash").id, :index => 5)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Cheat 720 Twist > Doublefull > Suicide Kip Up > Fulltwist Round")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 720 Twist").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Doublefull").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Suicide Kip Up").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Fulltwist Round").id, :index => 4)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Jackknife > Masterscoot > Cork Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Jackknife").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Masterscoot").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cork Doubleleg").id, :index => 3)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Butterfly Twist > Full Doubleleg > Front Flip > Front Sweep > Backside 1080")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Butterfly Twist").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Full Doubleleg").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Flip").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Front Sweep").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Backside 1080").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Narabong > Sideswipe > Aerial > Doubleleg Hook")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Narabong").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Sideswipe").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Aerial").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Doubleleg Hook").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat 900 > Hook > Jackknife")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Butterfly Twist").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Jackknife").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat Hyper 900 > Cartwheel > Fulltwist")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Butterfly Twist").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat Hyper 900").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Fulltwist").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "B-Twist Round > Hook > 540 > Cartwheel > Full Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("B-Twist Round").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Full Doubleleg").id, :index => 5)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Cheat 900 > Hook > TD Raiz > Flash Kick")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("TD Raiz").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Flash Kick").id, :index => 4)

Combo.create(:no_tricks => 7, :tricker_id => 1, :sequence => "Hook > Butterfly Twist > Cheat Hyper 900 > Aerial > Narabong > TD Raiz > Flash Kick")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Butterfly Twist").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat Hyper 900").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Aerial").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Narabong").id, :index => 5)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("TD Raiz").id, :index => 6)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Flash Kick").id, :index => 7)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Pop 360 > Parafuso > Doubleleg")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Pop 360").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Parafuso").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Doubleleg").id, :index => 3)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Cheat 720 > Tornado Kick > Cheat 900 > Hook > Aerial Hook Grab")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 720").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Tornado Kick").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Aerial Hook Grab").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Cartwheel > Back Flip > Back Roll > Back Handspring > Flash Kick")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cartwheel").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Back Flip").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Back Roll").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Back Handspring").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Flash Kick").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Pop 360 > Back Sweep > Narabong > TD Raiz > Flash Kick")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Pop 360").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Back Sweep").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Narabong").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 4)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Tornado Kick > Cheat 900 > Hook > Raiz > Flash Kick")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Tornado Kick").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 900").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Raiz").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Flash Kick").id, :index => 5)

Combo.create(:no_tricks => 5, :tricker_id => 1, :sequence => "Hook > 540 > TD Raiz > Gainer Switch > Corkscrew")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Hook").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("540").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("TD Raiz").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Gainer Switch").id, :index => 4)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Corkscrew").id, :index => 5)

Combo.create(:no_tricks => 4, :tricker_id => 1, :sequence => "Tornado Kick > Cheat 1080 > Raiz > Gainerflash")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Tornado Kick").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Cheat 1080").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Raiz").id, :index => 3)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Gainerflash").id, :index => 4)

Combo.create(:no_tricks => 3, :tricker_id => 1, :sequence => "Pop 720 Double > TD Raiz > Terada Grab")
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Pop 720 Double").id, :index => 1)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("TD Raiz").id, :index => 2)
Element.create(:combo_id => Combo.last.id, :trick_id => Trick.find_by_name("Terada Grab").id, :index => 3)

Video.create(:trick_id => Trick.find_by_name("540").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=QjOepEGrO8s")
Video.create(:trick_id => Trick.find_by_name("Aerial").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=NDpgshR6s4g")
Video.create(:trick_id => Trick.find_by_name("Pop 360").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=7_aDn5zdcPE")
Video.create(:trick_id => Trick.find_by_name("Butterfly Twist").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=G_bpuAz9eIM")
Video.create(:trick_id => Trick.find_by_name("Doubleleg").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=IgxGSUQ0jLg")
Video.create(:trick_id => Trick.find_by_name("Flash Kick").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=9w8owtFTihc")
Video.create(:trick_id => Trick.find_by_name("Jackknife").id, :tricker_id => 1, :url => "www.youtube.com/watch?v=dkRM3MeSRXI")